[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  PLAYWRIGHT_BROWSERS_PATH = "0"

# Note: Set these in Netlify Dashboard instead
# [context.production.environment]
#   MERCHANTWORDS_USERNAME = "your_username"
#   MERCHANTWORDS_PASSWORD = "your_password"